# Generated by Django 5.1.3 on 2024-11-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alumno_roll_maestro_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_entrega',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
